version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      alldependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - "@opendcs/opendcs-core-devs"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      alldependencies:
        patterns:
          - "*"
        update-types:
          - "major"
    reviewers:
      - "@opendcs/opendcs-core-devs"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      alldependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    reviewers:
      - "@opendcs/opendcs-core-devs"