[versions]
opendcs = "7.5.1-RC03"

servlet-api = "4.0.1" #Updating this further will require a change to the jakarta namespace.
slf4j = { strictly = "2.0.12" }
jersey = "2.40"

swagger = "2.2.28"
swagger-ui = "5.18.3"
jackson = "2.18.2"
selenium = "3.141.59"
nimbus = "9.41.1"
jwt = "4.4.0"
auto-service = "1.1.1"

#Test Dependencies
junit = "5.10.2"
mockito = "3.12.4"
byte-buddy = "1.15.3"
rest-assured = "5.5.0"
hamcrest = "3.0"
tomcat = "9.0.91"
commons-io = "2.11.0"
commons-lang = "2.5"

[libraries]
opendcs = { module = "org.opendcs:opendcs", version.ref = "opendcs" }
opendcs-api = { module = "org.opendcs:opendcs-api", version.ref = "opendcs" }

servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "servlet-api" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

json-jackson = { module = "org.glassfish.jersey.media:jersey-media-json-jackson", version.ref = "jersey" }
jersey-container-servlet = { module = "org.glassfish.jersey.containers:jersey-container-servlet", version.ref = "jersey" }
jersey-hk2 = { module = "org.glassfish.jersey.inject:jersey-hk2", version.ref = "jersey" }

jstl = { module = "javax.servlet:jstl", version = "1.2"}
swagger-jaxrs2 = { module = "io.swagger.core.v3:swagger-jaxrs2", version.ref = "swagger" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }

selenium = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "selenium" }
nimbus = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }
jwt = { module = "com.auth0:java-jwt", version.ref = "jwt" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }

#Test Dependencies
opendcs-integrationtesting-fixtures = { module = "org.opendcs:opendcs-integrationtesting-fixtures", version.ref = "opendcs"}
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
jersey-test = { module = "org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory", version.ref = "jersey" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
tomcat-embedded-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
tomcat-embedded-jasper = { module = "org.apache.tomcat.embed:tomcat-embed-jasper", version.ref = "tomcat" }
tomcat-jdbc = { module = "org.apache.tomcat:tomcat-jdbc", version.ref = "tomcat" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-lang = { module = "commons-lang:commons-lang", version.ref = "commons-lang" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j"}

# webjars
swagger-ui = { module ="org.webjars:swagger-ui", version.ref = "swagger-ui" }

[bundles]
tomcat = ["tomcat-embedded-core", "tomcat-embedded-jasper", "tomcat-jdbc"]
