name: Test Java Compatibility
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
      fail-fast: false
      max-parallel: 4
    name: Build on Java ${{ matrix.Java }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.4.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
      - name: Compile and Test
        run: ./gradlew build
