name: OWASP Zap
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  owasp-zap:
    name: Analyze with OWASP Zap API
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up JDK 8
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run OWASP Zap
        run: ./gradlew :opendcs-integration-test:owaspZap --stacktrace
      - name: Upload Full HTML Report
        uses: actions/upload-artifact@v5.0.0
        with:
          name: zap_report.html
          path: opendcs-integration-test/build/test-results/owasp_zap/zap_report.html
          retention-days: 1
          if-no-files-found: error
      - name: Trim Summary Report
        run: |
          sudo sed '/## Alert Detail/Q' opendcs-integration-test/build/test-results/owasp_zap/zap_report.md > ./zap_report_summary.md
      - name: Generate GitHub Job Summary
        uses: x-color/github-actions-job-summary@v0.1.1
        with:
          file: ./zap_report_summary.md
          vars: |
            empty: empty
