name: Publish Release Artifacts
on:
  release:
    types: [published]
jobs:
  build:
    permissions: write-all
    name: Attach Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
      - name: Build
        run: ./gradlew build
      - name: Bundle tarballs
        run: ./gradlew bundle
      - name: Attach OpenDCS REST API WAR file
        run: |
          gh release upload ${{ github.event.release.tag_name }} opendcs-rest-api/build/libs/opendcs-rest-api-${{ github.event.release.tag_name }}.war --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Attach OpenDCS Web Client WAR file
        run: |
          gh release upload ${{ github.event.release.tag_name }} opendcs-web-client/build/libs/opendcs-web-client-${{ github.event.release.tag_name }}.war --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
